plugins {
    id 'com.android.application'
}

android {
    namespace 'com.blockblast.game'
    compileSdk 34

    defaultConfig {
        applicationId "com.blockblast.game"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            // imzasız release yerine debug anahtarıyla imzala ki APK direkt kurulabilsin
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
